// <auto-generated />
using System;
using CloudServiceDownloaderAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CloudServiceDownloaderAPI.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20220607102012_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CloudServiceDownloaderAPI.Models.File", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("file_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DownloadTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("download_time");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("ShareLinkId")
                        .HasColumnType("bigint")
                        .HasColumnName("share_link_id");

                    b.HasKey("FileId")
                        .HasName("pk_files");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("ix_files_file_path");

                    b.HasIndex("ShareLinkId")
                        .HasDatabaseName("ix_files_share_link_id");

                    b.ToTable("files");
                });

            modelBuilder.Entity("CloudServiceDownloaderAPI.Models.ShareLink", b =>
                {
                    b.Property<long>("ShareLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("share_link_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CloudService")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_service");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_downloaded");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.HasKey("ShareLinkId")
                        .HasName("pk_share_links");

                    b.HasIndex("Link")
                        .IsUnique()
                        .HasDatabaseName("ix_share_links_link");

                    b.ToTable("share_links");
                });

            modelBuilder.Entity("CloudServiceDownloaderAPI.Models.File", b =>
                {
                    b.HasOne("CloudServiceDownloaderAPI.Models.ShareLink", "ShareLink")
                        .WithMany("Files")
                        .HasForeignKey("ShareLinkId")
                        .HasConstraintName("fk_files_share_links_share_link_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShareLink");
                });

            modelBuilder.Entity("CloudServiceDownloaderAPI.Models.ShareLink", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
